"""Shared constant values for agent configuration and policies."""

from __future__ import annotations

# Default LLM/tool budgets and timeouts (seconds)
DEFAULT_DB_BUDGET_TOKENS = 600
DEFAULT_DB_TIMEOUT_SECONDS = 15

DEFAULT_GRAPH_BUDGET_TOKENS = 800
DEFAULT_GRAPH_TIMEOUT_SECONDS = 20

DEFAULT_GRAPH_MODELING_BUDGET_TOKENS = 900
DEFAULT_GRAPH_MODELING_TIMEOUT_SECONDS = 25

DEFAULT_GRAPH_MEMORY_BUDGET_TOKENS = 700
DEFAULT_GRAPH_MEMORY_TIMEOUT_SECONDS = 18

DEFAULT_WEB_BUDGET_TOKENS = 400
DEFAULT_WEB_TIMEOUT_SECONDS = 30

DEFAULT_CUSTOM_AGENT_BUDGET_TOKENS = 512
DEFAULT_CUSTOM_AGENT_TIMEOUT_SECONDS = 18

DEFAULT_SEQUENTIAL_BUDGET_TOKENS = 768
DEFAULT_SEQUENTIAL_TIMEOUT_SECONDS = 20

# Evidence / retrieval limits
MAX_EVIDENCE_ITEMS = 6
MAX_SNIPPET_CHARS = 320
EVIDENCE_TOKEN_BUDGET = 1200
MAX_WEB_RESULTS = 4

# Agent Framework orchestrator defaults
MAX_WORKFLOW_ITERATIONS = 4
ACCEPTANCE_CONFIDENCE_THRESHOLD = 0.75
ACCEPTANCE_STRICT_MIN_SOURCES = 3
ACCEPTANCE_BASE_MIN_SOURCES = 2

# Common prefixes used when synthesizing task identifiers
DB_TASK_PREFIX = "db"
GRAPH_TASK_PREFIX = "graph"
WEB_TASK_PREFIX = "web"
CUSTOM_TASK_PREFIX = "agent"

__all__ = [
    "DEFAULT_DB_BUDGET_TOKENS",
    "DEFAULT_DB_TIMEOUT_SECONDS",
    "DEFAULT_GRAPH_BUDGET_TOKENS",
    "DEFAULT_GRAPH_TIMEOUT_SECONDS",
    "DEFAULT_GRAPH_MODELING_BUDGET_TOKENS",
    "DEFAULT_GRAPH_MODELING_TIMEOUT_SECONDS",
    "DEFAULT_GRAPH_MEMORY_BUDGET_TOKENS",
    "DEFAULT_GRAPH_MEMORY_TIMEOUT_SECONDS",
    "DEFAULT_WEB_BUDGET_TOKENS",
    "DEFAULT_WEB_TIMEOUT_SECONDS",
    "DEFAULT_CUSTOM_AGENT_BUDGET_TOKENS",
    "DEFAULT_CUSTOM_AGENT_TIMEOUT_SECONDS",
    "DEFAULT_SEQUENTIAL_BUDGET_TOKENS",
    "DEFAULT_SEQUENTIAL_TIMEOUT_SECONDS",
    "EVIDENCE_TOKEN_BUDGET",
    "MAX_EVIDENCE_ITEMS",
    "MAX_SNIPPET_CHARS",
    "MAX_WEB_RESULTS",
    "MAX_WORKFLOW_ITERATIONS",
    "ACCEPTANCE_CONFIDENCE_THRESHOLD",
    "ACCEPTANCE_STRICT_MIN_SOURCES",
    "ACCEPTANCE_BASE_MIN_SOURCES",
    "DB_TASK_PREFIX",
    "GRAPH_TASK_PREFIX",
    "WEB_TASK_PREFIX",
    "CUSTOM_TASK_PREFIX",
]
